import type { Galaxy } from './galaxyTypes'

// Rich mock fixture — a year of journal entries from a university student.
// Use this for frontend development until the real API is wired up.
export const MOCK_GALAXY: Galaxy = {
  meta: {
    id: 'mock-galaxy-2024',
    schemaVersion: 3,
    title: "Ava's Year — 2024",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 90,
    updatedAt: Date.now() - 1000 * 60 * 60 * 2,
    chapters: [
      {
        id: 'w1',
        uploadedAt: Date.now() - 1000 * 60 * 60 * 24 * 90,
        filename: 'journal_2024.txt',
        addedNodeIds: [
          'w1-arrival',
          'w1-new-beginnings',
          'w1-sarah',
          'w1-the-lab',
          'w1-thesis-starts',
          'w1-summer-drift',
          'w1-milan',
          'w1-the-letter',
          'w1-end-of-year',
          'w1-philosophy',
          'w1-rooftop-nights',
          'w1-first-semester',
          'w1-second-semester',
          'w1-full-year',
        ],
      },
    ],
  },
  source: {
    chapters: [
      {
        id: 'w1',
        kind: 'text',
        filename: 'journal_2024.txt',
        hash: 'abc123',
        excerpt: 'January 3rd. First day in the new city. The apartment smells like paint...',
        units: [
          { id: 'w1-s-0001', text: 'January 3rd. First day in the new city. The apartment smells like paint and the heating is broken but I feel electric. Something about starting over.' },
          { id: 'w1-s-0002', text: 'Met Sarah in the lab today. She explained the project in about 90 seconds and I understood maybe 40% of it but I nodded along. She has this way of making everything feel possible.' },
          { id: 'w1-s-0003', text: 'The thesis outline is done. My supervisor said it was "ambitious" which I think means either brilliant or delusional. Maybe both.' },
          { id: 'w1-s-0004', text: 'July. Summer is a strange limbo. The city empties and I fill the days with long walks and bad coffee and pages that go nowhere.' },
          { id: 'w1-s-0005', text: 'Milan arrived from Rome with two suitcases and enormous energy. We talked until 4am on the rooftop. He thinks the whole project is the wrong question.' },
          { id: 'w1-s-0006', text: 'A letter from home. My grandmother is unwell. I sat with it for a long time before I could write back.' },
          { id: 'w1-s-0007', text: 'December 31st. The year ends quietly. I know more than I did. I am not sure that is the same as understanding.' },
          { id: 'w1-s-0008', text: 'Philosophy seminar — we argued for two hours about whether consciousness could be substrate-independent. I left feeling unsettled in the best way.' },
          { id: 'w1-s-0009', text: 'Rooftop nights became a ritual. The city below, wine from the corner store, and arguments that mattered.' },
        ],
      },
    ],
  },
  knowledge: {
    clusters: [
      {
        id: 'w1-first-semester',
        chapter: 'w1',
        title: 'First Semester — Arrival',
        brief: 'Moving to a new city, starting the lab, forming early connections',
        sourceRefs: ['w1-s-0001', 'w1-s-0002', 'w1-s-0003'],
        groupIds: ['w1-grp-beginnings', 'w1-grp-people'],
      },
      {
        id: 'w1-second-semester',
        chapter: 'w1',
        title: 'Second Semester — Drift & Return',
        brief: 'Summer isolation, new arrivals, a letter from home, late-night rituals',
        sourceRefs: ['w1-s-0004', 'w1-s-0005', 'w1-s-0006', 'w1-s-0009'],
        groupIds: ['w1-grp-solitude', 'w1-grp-connections'],
      },
      {
        id: 'w1-full-year',
        chapter: 'w1',
        title: 'Full Year — Ideas & Endings',
        brief: 'Intellectual life, the thesis, philosophical shifts, year\'s end',
        sourceRefs: ['w1-s-0003', 'w1-s-0007', 'w1-s-0008'],
        groupIds: ['w1-grp-ideas'],
      },
    ],
    groups: [
      { id: 'w1-grp-beginnings', chapter: 'w1', title: 'New Beginnings', brief: 'The first weeks of arrival', sourceRefs: ['w1-s-0001'], clusterId: 'w1-first-semester', entryIds: ['w1-arrival', 'w1-new-beginnings'] },
      { id: 'w1-grp-people', chapter: 'w1', title: 'People', brief: 'Key people encountered', sourceRefs: ['w1-s-0002'], clusterId: 'w1-first-semester', entryIds: ['w1-sarah', 'w1-the-lab'] },
      { id: 'w1-grp-solitude', chapter: 'w1', title: 'Summer Solitude', brief: 'Empty city and drifting', sourceRefs: ['w1-s-0004'], clusterId: 'w1-second-semester', entryIds: ['w1-summer-drift', 'w1-the-letter'] },
      { id: 'w1-grp-connections', chapter: 'w1', title: 'Late Connections', brief: 'New arrivals and rooftop nights', sourceRefs: ['w1-s-0005', 'w1-s-0009'], clusterId: 'w1-second-semester', entryIds: ['w1-milan', 'w1-rooftop-nights'] },
      { id: 'w1-grp-ideas', chapter: 'w1', title: 'Ideas & Work', brief: 'Intellectual threads across the year', sourceRefs: ['w1-s-0003', 'w1-s-0008'], clusterId: 'w1-full-year', entryIds: ['w1-thesis-starts', 'w1-philosophy', 'w1-end-of-year'] },
    ],
    entries: [
      { id: 'w1-arrival', chapter: 'w1', title: 'First Day', brief: 'Moving into the new apartment, electric feeling of starting over', sourceRefs: ['w1-s-0001'], groupId: 'w1-grp-beginnings', kind: 'moment' },
      { id: 'w1-new-beginnings', chapter: 'w1', title: 'Starting Over', brief: 'A period of reinvention and possibility in a new city', sourceRefs: ['w1-s-0001'], groupId: 'w1-grp-beginnings', kind: 'period' },
      { id: 'w1-sarah', chapter: 'w1', title: 'Sarah', brief: 'Lab colleague — makes everything feel possible', sourceRefs: ['w1-s-0002'], groupId: 'w1-grp-people', kind: 'person' },
      { id: 'w1-the-lab', chapter: 'w1', title: 'The Research Lab', brief: 'The central location of the year\'s intellectual life', sourceRefs: ['w1-s-0002', 'w1-s-0003'], groupId: 'w1-grp-people', kind: 'place' },
      { id: 'w1-thesis-starts', chapter: 'w1', title: 'Thesis Begins', brief: 'Ambitious outline — ambitious or delusional, maybe both', sourceRefs: ['w1-s-0003'], groupId: 'w1-grp-ideas', kind: 'milestone' },
      { id: 'w1-summer-drift', chapter: 'w1', title: 'Summer Limbo', brief: 'Empty city, long walks, pages that go nowhere', sourceRefs: ['w1-s-0004'], groupId: 'w1-grp-solitude', kind: 'period' },
      { id: 'w1-milan', chapter: 'w1', title: 'Milan', brief: 'Arrived from Rome with two suitcases and enormous energy', sourceRefs: ['w1-s-0005'], groupId: 'w1-grp-connections', kind: 'person' },
      { id: 'w1-the-letter', chapter: 'w1', title: 'Letter From Home', brief: 'Grandmother is unwell — sat with it for a long time', sourceRefs: ['w1-s-0006'], groupId: 'w1-grp-solitude', kind: 'artifact' },
      { id: 'w1-end-of-year', chapter: 'w1', title: "Year's End", brief: 'Knowing more is not the same as understanding', sourceRefs: ['w1-s-0007'], groupId: 'w1-grp-ideas', kind: 'moment' },
      { id: 'w1-philosophy', chapter: 'w1', title: 'Consciousness Seminar', brief: 'Argued about substrate-independent consciousness — left unsettled in the best way', sourceRefs: ['w1-s-0008'], groupId: 'w1-grp-ideas', kind: 'theme' },
      { id: 'w1-rooftop-nights', chapter: 'w1', title: 'Rooftop Ritual', brief: 'City below, corner-store wine, arguments that mattered', sourceRefs: ['w1-s-0009'], groupId: 'w1-grp-connections', kind: 'place' },
    ],
  },
  relationships: {
    edges: [
      { id: 'e1', source: 'w1-sarah', target: 'w1-the-lab', type: 'involves', label: 'Both in the lab', weight: 0.9, sourceRefs: ['w1-s-0002'], chapter: 'w1' },
      { id: 'e2', source: 'w1-thesis-starts', target: 'w1-philosophy', type: 'related', label: 'Both questioning foundations', weight: 0.7, sourceRefs: ['w1-s-0003', 'w1-s-0008'], chapter: 'w1' },
      { id: 'e3', source: 'w1-arrival', target: 'w1-end-of-year', type: 'temporal', label: 'Start and end of the year', weight: 0.8, sourceRefs: ['w1-s-0001', 'w1-s-0007'], chapter: 'w1' },
      { id: 'e4', source: 'w1-milan', target: 'w1-rooftop-nights', type: 'involves', label: 'Milan sparked the rooftop ritual', weight: 0.85, sourceRefs: ['w1-s-0005', 'w1-s-0009'], chapter: 'w1' },
      { id: 'e5', source: 'w1-milan', target: 'w1-thesis-starts', type: 'contrasts', label: 'Milan thinks it is the wrong question', weight: 0.75, sourceRefs: ['w1-s-0005', 'w1-s-0003'], chapter: 'w1' },
      { id: 'e6', source: 'w1-summer-drift', target: 'w1-the-letter', type: 'temporal', label: 'Both during the summer isolation', weight: 0.6, sourceRefs: ['w1-s-0004', 'w1-s-0006'], chapter: 'w1' },
      { id: 'e7', source: 'w1-sarah', target: 'w1-rooftop-nights', type: 'involves', label: 'Sarah part of the rooftop circle', weight: 0.5, sourceRefs: ['w1-s-0002', 'w1-s-0009'], chapter: 'w1' },
      { id: 'e8', source: 'w1-first-semester', target: 'w1-second-semester', type: 'temporal', label: 'Chronological progression', weight: 0.9, sourceRefs: ['w1-s-0001', 'w1-s-0004'], chapter: 'w1' },
      { id: 'e9', source: 'w1-second-semester', target: 'w1-full-year', type: 'temporal', weight: 0.85, sourceRefs: ['w1-s-0004', 'w1-s-0007'], chapter: 'w1' },
      { id: 'e10', source: 'w1-philosophy', target: 'w1-end-of-year', type: 'causal', label: 'The seminar reframed the year\'s end', weight: 0.65, sourceRefs: ['w1-s-0008', 'w1-s-0007'], chapter: 'w1' },
    ],
  },
  wraps: {
    'w1-first-semester': {
      nodeId: 'w1-first-semester',
      level: 'cluster',
      headline: 'The month everything started',
      summary: 'A new city, a new lab, new faces. The first semester was electric — full of possibility and the quiet terror of starting over. Sarah appeared. The thesis took shape.',
      mood: 'energetic',
      color: '#7c9ef8',
      stats: [{ label: 'Entries', value: '4' }, { label: 'People', value: '2' }, { label: 'Places', value: '1' }],
      highlights: ['Apartment smells like paint — the good kind of broken', 'Sarah explained the project and made it sound inevitable', '"Ambitious" — supervisor code for either genius or disaster'],
      derivatives: [{ sourceRef: 'w1-s-0001', quote: 'I feel electric. Something about starting over.' }, { sourceRef: 'w1-s-0002', quote: 'She has this way of making everything feel possible.' }],
      sourceRefs: ['w1-s-0001', 'w1-s-0002', 'w1-s-0003'],
      dateRange: 'January – April 2024',
      topEntries: ['w1-sarah', 'w1-thesis-starts', 'w1-arrival'],
      themes: ['New beginnings', 'Intellectual ambition', 'Human connection'],
    } as import('./galaxyTypes').ClusterWrap,
    'w1-second-semester': {
      nodeId: 'w1-second-semester',
      level: 'cluster',
      headline: 'The city emptied and I filled it',
      summary: 'Summer stripped the city bare. Long walks, stalled pages, a letter that arrived like a stone. Then Milan came with his energy and the rooftop became a ritual.',
      mood: 'bittersweet',
      color: '#e8a07a',
      stats: [{ label: 'Entries', value: '4' }, { label: 'People', value: '1' }, { label: 'Key moments', value: '2' }],
      highlights: ['Summer is a strange limbo', 'Milan: two suitcases, enormous energy, 4am on the rooftop', 'A letter from home — sat with it for a long time'],
      derivatives: [{ sourceRef: 'w1-s-0004', quote: 'The city empties and I fill the days with long walks and bad coffee.' }, { sourceRef: 'w1-s-0005', quote: 'He thinks the whole project is the wrong question.' }],
      sourceRefs: ['w1-s-0004', 'w1-s-0005', 'w1-s-0006', 'w1-s-0009'],
      dateRange: 'May – August 2024',
      topEntries: ['w1-milan', 'w1-the-letter', 'w1-rooftop-nights'],
      themes: ['Isolation', 'Unexpected connection', 'Distance from home'],
    } as import('./galaxyTypes').ClusterWrap,
    'w1-full-year': {
      nodeId: 'w1-full-year',
      level: 'cluster',
      headline: 'Knowing more is not understanding',
      summary: 'The thesis grew ambitious and dangerous. A philosophy seminar reframed everything. By year\'s end, knowledge felt different from comprehension — and that distinction became the point.',
      mood: 'curious',
      color: '#a78bfa',
      stats: [{ label: 'Entries', value: '3' }, { label: 'Ideas', value: '2' }, { label: 'Questions opened', value: '∞' }],
      highlights: ['"Ambitious" — could go either way', 'Consciousness argued to a beautiful impasse', 'December 31st: knowing more is not the same as understanding'],
      derivatives: [{ sourceRef: 'w1-s-0008', quote: 'I left feeling unsettled in the best way.' }, { sourceRef: 'w1-s-0007', quote: 'I know more than I did. I am not sure that is the same as understanding.' }],
      sourceRefs: ['w1-s-0003', 'w1-s-0007', 'w1-s-0008'],
      dateRange: 'September – December 2024',
      topEntries: ['w1-philosophy', 'w1-thesis-starts', 'w1-end-of-year'],
      themes: ['Intellectual growth', 'Uncertainty as progress', 'The limits of knowledge'],
    } as import('./galaxyTypes').ClusterWrap,
    'w1-sarah': {
      nodeId: 'w1-sarah',
      level: 'entry',
      headline: 'She made it all feel possible',
      summary: 'Sarah arrived first in the lab and left the strongest impression. Her clarity was contagious — 90 seconds to explain the project, and the room shifted around her.',
      mood: 'energetic',
      color: '#60a5fa',
      stats: [{ label: 'Mentions', value: '3' }, { label: 'First met', value: 'January' }],
      highlights: ['Explained the project in 90 seconds', 'I understood maybe 40% — and it felt like enough', 'She became the lab\'s centre of gravity'],
      body: 'Sarah is the kind of person who simplifies without flattening. She walked into the lab and immediately started explaining the project — rapid, confident, generous. I understood about 40% of it but I nodded along because something about her delivery made the gap feel temporary. Over the semester she became the lab\'s centre of gravity: the one people brought problems to, the one who somehow always had time. Her ability to make things feel possible without making them feel easy is a rare quality.',
      keyFacts: [{ label: 'Role', value: 'Research colleague' }, { label: 'First encounter', value: 'January 2024, the lab' }],
      connections: [{ targetId: 'w1-the-lab', reason: 'Sarah is at the center of the lab community' }, { targetId: 'w1-rooftop-nights', reason: 'Sarah became part of the rooftop circle' }],
      derivatives: [{ sourceRef: 'w1-s-0002', quote: 'She explained the project in about 90 seconds and I understood maybe 40% of it but I nodded along.' }, { sourceRef: 'w1-s-0002', quote: 'She has this way of making everything feel possible.' }],
      sourceRefs: ['w1-s-0002'],
    } as import('./galaxyTypes').EntryWrap,
    'w1-milan': {
      nodeId: 'w1-milan',
      level: 'entry',
      headline: 'Two suitcases and a challenge',
      summary: 'Milan arrived from Rome mid-summer with the kind of energy that rearranges a room. He questioned the thesis from first principles and turned midnight conversations into a ritual.',
      mood: 'energetic',
      color: '#f97316',
      stats: [{ label: 'Arrived', value: 'July' }, { label: 'Origin', value: 'Rome' }, { label: 'Rooftop hours', value: '∞' }],
      highlights: ['Two suitcases, enormous energy', 'Talked until 4am on the first night', 'Said the whole project was the wrong question — and made me wonder'],
      body: 'Milan showed up mid-summer from Rome with two suitcases and a disposition that refused to slow down. He had opinions about everything and the curiosity to back them up. On his first night we ended up on the rooftop talking until 4am — he challenged the thesis not out of hostility but out of genuine intellectual restlessness. "It\'s the wrong question," he said, and then spent an hour explaining what the right question might be. Whether he was correct is still open. What is certain is that after that night, the rooftop became a regular thing.',
      keyFacts: [{ label: 'Origin', value: 'Rome, Italy' }, { label: 'Arrived', value: 'July 2024' }],
      connections: [{ targetId: 'w1-rooftop-nights', reason: 'Milan initiated the rooftop ritual' }, { targetId: 'w1-thesis-starts', reason: 'Milan challenged the thesis direction' }],
      derivatives: [{ sourceRef: 'w1-s-0005', quote: 'Milan arrived from Rome with two suitcases and enormous energy.' }, { sourceRef: 'w1-s-0005', quote: 'He thinks the whole project is the wrong question.' }],
      sourceRefs: ['w1-s-0005'],
    } as import('./galaxyTypes').EntryWrap,
    'w1-philosophy': {
      nodeId: 'w1-philosophy',
      level: 'entry',
      headline: 'Unsettled in the best way',
      summary: 'A philosophy seminar on substrate-independent consciousness became a two-hour productive argument. The kind that leaves you questioning assumptions you didn\'t know you had.',
      mood: 'curious',
      color: '#c084fc',
      stats: [{ label: 'Duration', value: '2 hours' }, { label: 'Conclusion', value: 'None, intentionally' }],
      highlights: ['Substrate-independent consciousness — still open', 'Left feeling unsettled, which was the point', 'Best kind of argument: no winner'],
      body: 'The philosophy seminar started with a deceptively simple question: could consciousness be substrate-independent? Two hours later we had covered Chalmers, Tononi, computational theories of mind, and the hard problem — and reached nothing like consensus. That was exactly right. The best seminars don\'t resolve; they recalibrate. Walking home afterwards I kept turning over the question and noticing how it kept connecting to the thesis, to Sarah\'s research, to Milan\'s challenge. Some questions are more generative than their answers.',
      keyFacts: [{ label: 'Topic', value: 'Substrate-independent consciousness' }, { label: 'Outcome', value: 'Productive impasse' }],
      connections: [{ targetId: 'w1-thesis-starts', reason: 'The seminar questions echoed through the thesis' }, { targetId: 'w1-end-of-year', reason: 'Reframed the meaning of "knowing"' }],
      derivatives: [{ sourceRef: 'w1-s-0008', quote: 'we argued for two hours about whether consciousness could be substrate-independent.' }, { sourceRef: 'w1-s-0008', quote: 'I left feeling unsettled in the best way.' }],
      sourceRefs: ['w1-s-0008'],
    } as import('./galaxyTypes').EntryWrap,
    'w1-arrival': {
      nodeId: 'w1-arrival',
      level: 'entry',
      headline: 'Paint, cold, electricity',
      summary: 'The first day in the new city. A broken heater and an apartment smelling of paint — but an overwhelming sense of possibility in the act of beginning again.',
      mood: 'energetic',
      color: '#34d399',
      stats: [{ label: 'Date', value: 'January 3rd, 2024' }],
      highlights: ['Apartment smells like paint', 'Heating is broken', 'I feel electric'],
      body: 'January 3rd. The apartment smells like paint and the heating doesn\'t work and it is perfect. There is something about arriving somewhere new with only what you can carry that strips everything to signal. No history here, no context that precedes you. Just the first day of something that hasn\'t decided what it is yet. I spent the evening unpacking slowly, deliberately, making it mine.',
      keyFacts: [{ label: 'Date', value: 'January 3rd, 2024' }, { label: 'Location', value: 'New city apartment' }],
      connections: [{ targetId: 'w1-end-of-year', reason: 'Bookends the year — arrival to departure' }, { targetId: 'w1-new-beginnings', reason: 'Arrival is the physical start of the new beginning period' }],
      derivatives: [{ sourceRef: 'w1-s-0001', quote: 'The apartment smells like paint and the heating is broken but I feel electric.' }, { sourceRef: 'w1-s-0001', quote: 'Something about starting over.' }],
      sourceRefs: ['w1-s-0001'],
    } as import('./galaxyTypes').EntryWrap,
    'w1-rooftop-nights': {
      nodeId: 'w1-rooftop-nights',
      level: 'entry',
      headline: 'Arguments that mattered',
      summary: 'The rooftop became a ritual — city lights below, wine from the corner store, conversations that pushed back on everything. This is where the year\'s best thinking happened.',
      mood: 'nostalgic',
      color: '#f59e0b',
      stats: [{ label: 'Started', value: 'July' }, { label: 'Regularity', value: 'Weekly' }, { label: 'Participants', value: '3–5' }],
      highlights: ['City below, wine from the corner store', 'Arguments that mattered', 'The ritual that survived the year'],
      body: 'After Milan\'s first night, the rooftop became a fixture. Not every week, but enough to call it a ritual. The cast shifted — sometimes Sarah, sometimes others from the lab, always Milan when he was in town. The city below was incidental backdrop. What made it was the permission to be unfinished out loud — to argue without having to win, to speculate without having to be right. Some of the year\'s best thinking happened up there with bad wine and a good view.',
      keyFacts: [{ label: 'Location', value: 'Rooftop, city apartment building' }, { label: 'Season', value: 'Summer through winter' }],
      connections: [{ targetId: 'w1-milan', reason: 'Milan started the rooftop tradition' }, { targetId: 'w1-sarah', reason: 'Sarah was a rooftop regular' }],
      derivatives: [{ sourceRef: 'w1-s-0009', quote: 'The city below, wine from the corner store, and arguments that mattered.' }],
      sourceRefs: ['w1-s-0009'],
    } as import('./galaxyTypes').EntryWrap,
    'w1-the-letter': {
      nodeId: 'w1-the-letter',
      level: 'entry',
      headline: 'A stone in the mailbox',
      summary: 'A letter from home arrived during the summer emptiness. Grandmother is unwell. Some words take a long time to absorb.',
      mood: 'melancholic',
      color: '#94a3b8',
      stats: [{ label: 'Arrived', value: 'Summer 2024' }],
      highlights: ['Some letters arrive like weight', 'Sat with it before writing back', 'Home, suddenly very far'],
      body: 'The letter arrived on an ordinary afternoon. My grandmother is unwell — the words on the page were simple and the meaning was large. I sat with it for a long time before I could think about what to write back. The summer was already quiet but this made it quieter. It\'s strange how distance works: most of the time it is an abstraction. Then something happens and it becomes physical, a real space between you and the people you came from.',
      keyFacts: [{ label: 'Sender', value: 'Family, from home' }, { label: 'Timing', value: 'Mid-summer, during isolation period' }],
      connections: [{ targetId: 'w1-summer-drift', reason: 'Arrived during the summer drift, deepening it' }],
      derivatives: [{ sourceRef: 'w1-s-0006', quote: 'A letter from home. My grandmother is unwell. I sat with it for a long time before I could write back.' }],
      sourceRefs: ['w1-s-0006'],
    } as import('./galaxyTypes').EntryWrap,
    'w1-thesis-starts': {
      nodeId: 'w1-thesis-starts',
      level: 'entry',
      headline: '"Ambitious" — supervisor code',
      summary: 'The thesis outline was finished and pronounced "ambitious" by the supervisor. The word lands differently depending on the tone. This one was unreadable.',
      mood: 'determined',
      color: '#6ee7b7',
      stats: [{ label: 'Status', value: 'Outline complete' }, { label: 'Supervisor verdict', value: 'Ambitious' }],
      highlights: ['"Ambitious" — brilliant or delusional, maybe both', 'The outline is done', 'The work is beginning'],
      body: 'The thesis outline is finished. Three months of reading and circling and draft-writing condensed into twelve pages of argument. My supervisor read it and said it was "ambitious." I have been sitting with that word. It can mean two opposite things: that the project is genuinely reaching for something important, or that it is overextended and due for a reckoning. Maybe both are true at once. The outline feels like a promise I have made to myself that I am not sure I can keep. That is probably the right relationship to have with it at this stage.',
      keyFacts: [{ label: 'Stage', value: 'Outline complete' }, { label: 'Supervisor response', value: '"Ambitious"' }],
      connections: [{ targetId: 'w1-philosophy', reason: 'Philosophy seminar fed directly into the thesis questions' }, { targetId: 'w1-milan', reason: 'Milan challenged the thesis direction' }],
      derivatives: [{ sourceRef: 'w1-s-0003', quote: 'My supervisor said it was "ambitious" which I think means either brilliant or delusional. Maybe both.' }],
      sourceRefs: ['w1-s-0003'],
    } as import('./galaxyTypes').EntryWrap,
    'w1-end-of-year': {
      nodeId: 'w1-end-of-year',
      level: 'entry',
      headline: 'Knowing is not understanding',
      summary: 'December 31st, quiet and clear. A year of accumulation. The distinction between knowing more and actually understanding something felt, for the first time, important.',
      mood: 'bittersweet',
      color: '#818cf8',
      stats: [{ label: 'Date', value: 'December 31st, 2024' }],
      highlights: ['The year ends quietly', 'I know more than I did', 'Knowing more is not understanding'],
      body: 'December 31st. The year ends the way years should — quietly, without fanfare, with a sense that you have arrived somewhere but cannot yet say where. I know more than I did in January. More about the project, more about how to work, more about the people around me. But more is not the same as deeper, and accumulation is not the same as comprehension. I think that distinction — knowing versus understanding — might be the year\'s real finding.',
      keyFacts: [{ label: 'Date', value: 'December 31st, 2024' }],
      connections: [{ targetId: 'w1-arrival', reason: 'Closing bookend to the opening arrival' }, { targetId: 'w1-philosophy', reason: 'Philosophy seminar planted this distinction' }],
      derivatives: [{ sourceRef: 'w1-s-0007', quote: 'I know more than I did. I am not sure that is the same as understanding.' }],
      sourceRefs: ['w1-s-0007'],
    } as import('./galaxyTypes').EntryWrap,
    'w1-summer-drift': {
      nodeId: 'w1-summer-drift',
      level: 'entry',
      headline: 'Long walks, bad coffee, nowhere pages',
      summary: 'The city emptied in summer. The work stalled and the days stretched. A productive kind of lostness, in retrospect.',
      mood: 'melancholic',
      color: '#fbbf24',
      stats: [{ label: 'Duration', value: 'June – July' }, { label: 'Pages written', value: 'Few that stayed' }],
      highlights: ['The city empties', 'Long walks and bad coffee', 'Pages that go nowhere'],
      body: 'June and July in a university city are a different species of time. The usual social structure evaporates and you are left with yourself and your work and the question of whether you are the kind of person who can function without external scaffolding. The answer, it turns out, is: partially. I walked a lot. I wrote pages that I deleted. I drank a lot of mediocre coffee from the kiosk near the canal. In retrospect it was a necessary fallow period. The work needed to not work for a while.',
      keyFacts: [{ label: 'Season', value: 'Summer 2024' }, { label: 'Mode', value: 'Fallow, drifting' }],
      connections: [{ targetId: 'w1-the-letter', reason: 'Letter arrived during this drift, deepening the quiet' }],
      derivatives: [{ sourceRef: 'w1-s-0004', quote: 'Summer is a strange limbo. The city empties and I fill the days with long walks and bad coffee and pages that go nowhere.' }],
      sourceRefs: ['w1-s-0004'],
    } as import('./galaxyTypes').EntryWrap,
    'w1-new-beginnings': {
      nodeId: 'w1-new-beginnings',
      level: 'entry',
      headline: 'A season of reinvention',
      summary: 'The first semester was not just a beginning — it was the project of actively becoming something. The city, the lab, the people: all new scaffolding for a self in construction.',
      mood: 'energetic',
      color: '#4ade80',
      stats: [{ label: 'Duration', value: 'Jan – Apr 2024' }],
      highlights: ['Everything is new', 'No context precedes you', 'The freedom of the blank slate'],
      body: 'Starting over is a project. It takes deliberate effort to let the blank slate be blank — to resist importing the habits and assumptions and self-conceptions from the previous context. The first semester was an exercise in that discipline. New city, new institution, new colleagues: an enforced freshness. I found it clarifying. The freedom to not yet have a reputation, to be seen without preconception, to construct rather than maintain.',
      keyFacts: [{ label: 'Period', value: 'January–April 2024' }],
      connections: [{ targetId: 'w1-arrival', reason: 'Arrival was the physical trigger for this period' }],
      derivatives: [{ sourceRef: 'w1-s-0001', quote: 'Something about starting over.' }],
      sourceRefs: ['w1-s-0001'],
    } as import('./galaxyTypes').EntryWrap,
    'w1-the-lab': {
      nodeId: 'w1-the-lab',
      level: 'entry',
      headline: 'The room where the year happened',
      summary: 'The research lab became the year\'s gravitational centre. Work, people, arguments — everything that mattered passed through it.',
      mood: 'determined',
      color: '#38bdf8',
      stats: [{ label: 'Type', value: 'Research lab' }, { label: 'Role', value: 'Central location' }],
      highlights: ['Where Sarah explained everything', 'Where the thesis took shape', 'The year\'s centre of gravity'],
      body: 'The lab is a mid-size room on the third floor with too many whiteboards and not enough windows. By February it had become the centre of the year. Not just for work — though it was that too — but for the kind of thinking that happens when you are surrounded by people who are also trying to figure something out. The best conversations started there. The worst drafts got written there. It was a room that asked something of you, and most days you tried to deliver.',
      keyFacts: [{ label: 'Location', value: 'Third floor, research building' }, { label: 'Significance', value: 'Intellectual home base' }],
      connections: [{ targetId: 'w1-sarah', reason: 'Sarah was central to the lab dynamic' }, { targetId: 'w1-thesis-starts', reason: 'Thesis work happened here' }],
      derivatives: [{ sourceRef: 'w1-s-0002', quote: 'Met Sarah in the lab today. She explained the project in about 90 seconds.' }],
      sourceRefs: ['w1-s-0002'],
    } as import('./galaxyTypes').EntryWrap,
  },
  exploration: {
    visited: {},
    bookmarked: [],
  },
  pipeline: {
    ingest: { status: 'complete', startedAt: Date.now() - 5000, completedAt: Date.now() - 4000 },
    structure: { status: 'complete', startedAt: Date.now() - 4000, completedAt: Date.now() - 3000 },
    wraps: { status: 'complete', startedAt: Date.now() - 3000, completedAt: Date.now() - 1000 },
    coverage: { status: 'complete', startedAt: Date.now() - 1000, completedAt: Date.now() - 500 },
  },
}
